name: CI-CD Inference Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt

      - name: Train model
        run: |
          python scripts/train.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: Model/model.pkl

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: Metrics/metrics.json

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model
        uses: actions/download-artifact@v4
        with:
          name: model
          path: Model/

      - name: Download metrics
        uses: actions/download-artifact@v4
        with:
          name: metrics
          path: Metrics/

      - name: Compare metrics
        id: compare
        run: |
          CUR_MSE=$(jq .mse Metrics/metrics.json)
          CUR_R2=$(jq .r2 Metrics/metrics.json)

          echo "Current MSE: $CUR_MSE"
          echo "Current R2: $CUR_R2"

          if (( $(echo "$CUR_MSE < ${{ vars.BEST_MSE }} && $CUR_R2 > ${{ vars.BEST_R2 }}" | bc -l) )); then
            echo "deploy=true" >> $GITHUB_ENV
          else
            echo "deploy=false" >> $GITHUB_ENV
            echo "2022BCS0034 ---- Metric did not improve"
          fi

      - name: Login to Docker Hub
        if: env.deploy == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: env.deploy == 'true'
        run: |
          docker build -t varuna10/varunmohanbcs34-wine-quality:latest .
          docker push varuna10/varunmohanbcs34-wine-quality:latest

      - name: Update BEST metrics
        if: env.deploy == 'true'
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/BEST_MSE \
            -d "{\"name\":\"BEST_MSE\",\"value\":\"$CUR_MSE\"}"

          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/BEST_R2 \
            -d "{\"name\":\"BEST_R2\",\"value\":\"$CUR_R2\"}"
